title: ישיבת בית הלוי - ראש העין
description: האתר הרשמי של ישיבת בית הלוי בראש העין בראשות הגה"צ אבנר עפג'ין שליט"א. באתר תוכלו למצוא חדשות, עדכונים, גלריות תמונות מאירועים בישיבה ועוד.
lang: he
direction: rtl
# Disable Jekyll processing for folders starting with underscores if needed, 
# but here we just want to override the default site metadata.
